#!/bin/sh

set -e
set -x

which jq

bin=$(npm bin)

$bin/trash node_modules &>/dev/null
git pull --rebase
npm install
npm test
cp package.json _package.json
bump=`$bin/conventional-recommended-bump -p angular`
echo ${1:-$bump}
npm --no-git-tag-version version ${1:-$bump} &>/dev/null
$bin/conventional-changelog -i CHANGELOG.md -w -p angular
git add CHANGELOG.md
version=`cat package.json | cat package.json | jq -r '.version'`
git commit -m "docs(CHANGELOG): $version" &&
mv -f _package.json package.json &&
npm version ${1:-$bump} -m "chore(release): %s"
git push --follow-tags &&
$bin/conventional-github-releaser -p angular
npm publish
